In [1]:
pip install numpy pandas


^C
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
import pandas as pd

In [13]:
#pandas practice
#Creating a dataframe
import pandas

mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2]
}

myvar = pandas.DataFrame(mydataset)

print(myvar)


    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2


In [4]:
#Series in pandas
import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a)

print(myvar)

0    1
1    7
2    2
dtype: int64


In [5]:
print(myvar[0])

1


In [7]:
#Creating our own labels
import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a, index = ["x", "y", "z"])

print(myvar)
print(myvar["y"])

x    1
y    7
z    2
dtype: int64
7


In [8]:
#Create a simple Pandas Series from a dictionary:

import pandas as pd

calories = {"day1": 420, "day2": 380, "day3": 390}

myvar = pd.Series(calories)

print(myvar)

day1    420
day2    380
day3    390
dtype: int64


In [9]:
#Create a DataFrame from two Series:

import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

myvar = pd.DataFrame(data)

print(myvar)

   calories  duration
0       420        50
1       380        40
2       390        45


In [14]:
# a list of names to give each row a name:

import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

df = pd.DataFrame(data, index = ["day1", "day2", "day3"])

print(df) 

      calories  duration
day1       420        50
day2       380        40
day3       390        45


In [16]:
#Load the CSV into a DataFrame:
# df = pd.read_csv('data.csv')

# print(df.to_string()) 

In [ ]:
#Check the number of maximum returned rows:
# print(pd.options.display.max_rows) 

In [17]:
#numpy basics
arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [18]:
print(np.__version__)

2.5.1


In [20]:
#NumPy Creating Arrays( 2-D array 
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)



[[1 2 3]
 [4 5 6]]


In [21]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [22]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [23]:
# Access Array Elements
arr = np.array([1, 2, 3, 4])

print(arr[0])


1


In [24]:
print(arr[2] + arr[3])

7


In [25]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])


2nd element on 1st row:  2


In [27]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])
print('Last element from 2nd dim: ', arr[1, -1])

6
Last element from 2nd dim:  [10 11 12]


In [29]:
# Array Slicing
print(arr[1:5])
print(arr[-3:-1])
print(arr[1:5:2])

[[[ 7  8  9]
  [10 11 12]]]
[[[1 2 3]
  [4 5 6]]]
[[[ 7  8  9]
  [10 11 12]]]


In [30]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]
